### ISSUE TITLE
why does SNMP QOS queue not follow CLI queue or vice-versa?

### ISSUE THREAD

**Issue by samaity** [Azure/sonic-snmpagent#123]
**Description**

SNMP QOS queue doesn't follow CLI queue.
That means SNMP queues are 1-10 (can be seen via **snmpwalk** with oid 1.3.6.1.4.1.9.9.580.1.5.5.1)
and CLI queues are 0-9 which can be noticed via **queuestat**.

If I understand correctly, as per this [line](https://github.com/Azure/sonic-snmpagent/blob/f5b70df68b0d23bfa409204c4f9588df55855a20/src/sonic_ax_impl/mibs/vendor/cisco/ciscoSwitchQosMIB.py#L133) in [ciscoSwitchQosMib.py](https://github.com/Azure/sonic-snmpagent/blob/master/src/sonic_ax_impl/mibs/vendor/cisco/ciscoSwitchQosMIB.py#L133) script, it's designed in a way, the query will be 1-based.
```
mib_oid = (if_index, int(DirectionTypes.EGRESS), (queue % pq_count) + 1, counter_mib_id)
```
my question is that as source of both the queries is **`COUNTER DB`**, why can't it make it symmetrical. it will be easier to troubleshoot or collecting the metrics on whether to start from 1 or 0.

**Describe the results you received:**

Currently, SNMP QOS queue doesn't follow CLI queue or vice verse.

**Describe the results you expected:**

My question is whether we can make it the same whether it's 1 based or 0 based on both the places.

**Comment by samaity** [comment]
@qiluo-msft , do you have any idea?

**Comment by qiluo-msft** [comment]
https://tools.ietf.org/html/rfc2578
```
   Instances identified by use of integer-valued objects should be
   numbered starting from one (i.e., not from zero).  The use of zero as
   a value for an integer-valued index object should be avoided, except
   in special cases.
```
This is SNMP convention. All others are following SAI conventions.
