### ISSUE TITLE
bug: .1.3.6.1.2.1.2.2.1.2.1

### ISSUE THREAD

**Issue by qiluo-msft** [Azure/sonic-snmpagent#14]
.1.3.6.1.2.1.2.2.1.2.1

It returns nothing, but

    .1.3.6.1.2.1.2.2.1.2

return a list with ".1"

**Comment by lguohan** [comment]
@qiluo-msft , is this resolved?

**Comment by qiluo-msft** [comment]
Yes, just checked the latest build and it is resolved.
