### ISSUE TITLE
[201811] build failure due to psutil version change, 5.7.0 is fine, higher version causes failure

### ISSUE THREAD

**Issue by dzhangalibaba** [Azure/sonic-snmpagent#150]
we need fix psutil version, looks 201811 branch uses python3.4, on master branch it is python3.6, then higher psutil version 5.7.1 is fine 

Installed /sonic/src/sonic-snmpagent/python_arptable-0.0.2-py3.4.egg
Searching for psutil>=4.0
Reading https://pypi.python.org/simple/psutil/
Best match: psutil 5.7.1
Downloading https://files.pythonhosted.org/packages/2c/5c/cb95a715fb635e1ca858ffb8c50a523a16e2dc06aa3e207ab73cb93516af/psutil-5.7.1.tar.gz#sha256=4ef6845b35e152e6937d4f28388c2440ca89a0089ced0a30a116fa3ceefdfa3a
Processing psutil-5.7.1.tar.gz
Writing /tmp/easy_install-k41w49qa/psutil-5.7.1/setup.cfg
Running psutil-5.7.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-k41w49qa/psutil-5.7.1/egg-dist-tmp-eaxqyor5
/usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
error: Setup script exited with error in psutil setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
[  FAIL LOG END  ] [ target/python-wheels/asyncsnmp-2.1.0-py3-none-any.whl ]
make: *** [target/python-wheels/asyncsnmp-2.1.0-py3-none-any.whl] Error 1
slave.mk:402: recipe for target 'target/python-wheels/asyncsnmp-2.1.0-py3-none-any.whl' failed
Makefile.work:131: recipe for target 'target/sonic-broadcom.bin' failed
make[1]: *** [target/sonic-broadcom.bin] Error 2
make[1]: Leaving directory '/data/johnar/workspace/broadcom/buildimage-brcm-201811'
Makefile:6: recipe for target 'target/sonic-broadcom.bin' failed
make: *** [target/sonic-broadcom.bin] Error 2
+++ --- Making target/sonic-aboot-broadcom.swi --- +++
BLDENV=stretch make -f Makefile.work stretch
make[1]: Entering directory '/data/johnar/workspace/broadcom/buildimage-brcm-201811'
SONiC Build System

**Comment by qiluo-msft** [comment]
Is it related to this merged PR https://github.com/Azure/sonic-snmpagent/pull/152 ?

**Comment by dzhangalibaba** [comment]
> Is it related to this merged PR #152 ?

yes. That will fix this.
