### ISSUE TITLE
ERR snmpd[18]: Cannot statfs /root/host: Permission denied

### ISSUE THREAD

**Issue by stcheng** [Azure/sonic-snmpagent#22]
```
 ERR snmpd[18]: Cannot statfs /root/host: Permission denied
 ERR snmpd[18]: Cannot statfs /root/dev: Permission denied
 ERR snmpd[18]: Cannot statfs /root/dev/pts: Permission denied
```

**Comment by stcheng** [comment]
https://askubuntu.com/questions/828769/snmpd-cannot-statfs-directory

**Comment by liatgrozovik** [comment]
If they are unrelated and should never be caught they should be added to the ignore list files.
if they are not related to specific test the relevant test ignore file should be updated.

Please review the common ignore files and update it if needed.

**Comment by lguohan** [comment]
the root cause is those directories are not available after we do aufs. @qiluo-msft, is there any way to not show the /root/dev, /root/dev/pts, /root/host in the /proc/mounts?

```
admin@str-s6000-acs-7:/var/log$ sudo grep root /proc/mounts
rootfs / rootfs rw 0 0
udev /root/dev devtmpfs rw,relatime,size=10240k,nr_inodes=1020200,mode=755 0 0
devpts /root/dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
/dev/sda3 /root/host ext4 rw,relatime,data=ordered 0 0
/dev/loop0 /root squashfs ro,relatime 0 0
```

**Comment by xinliu-seattle** [comment]
Reopen this. But low priority.
