### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'decode'

### ISSUE THREAD

**Issue by stcheng** [Azure/sonic-snmpagent#79]
In the latest master image, the newly pulled in commit: https://github.com/Azure/sonic-snmpagent/pull/72 will cause issue when the information cannot be retrieved from the database.

`Aug  9 23:29:26.815914 SONiC ERR snmp/snmp-subagent [ax_interface] ERROR: MIBUpdater.start() caught an unexpected exception during update_data()#012Traceback (most recent call last):#012  File "/usr/local/lib/python3.6/dist-packages/ax_interface/mib.py", line 40, in start#012    self.reinit_data()#012  File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/mibs/ieee802_1ab.py", line 270, in reinit_data#012    b'lldp_loc_man_addr').decode('utf-8')#012AttributeError: 'NoneType' object has no attribute 'decode'`

**Comment by stcheng** [comment]
@mykolaf could you check this issue?

**Comment by mykolaf** [comment]
sure, https://github.com/Azure/sonic-snmpagent/pull/80

**Comment by stcheng** [comment]
thanks @mykolaf
